import type { Department, Industry, Objective, OpportunityCategory } from "@/types/discovery";

export interface OpportunityTemplate {
  id: string;
  title: string;
  description: string;
  category: OpportunityCategory;
  baseImpact: number;
  baseEffort: number;
  estimatedROI: string;
  matchIndustries: Industry[];
  matchDepartments: Department[];
  matchObjectives: Objective[];
  matchBottleneckIds: string[];
}

export const OPPORTUNITY_CATALOG: OpportunityTemplate[] = [
  {
    id: "doc_processing",
    title: "Intelligent Document Processing",
    description: "Use AI to automatically extract, classify, and route information from documents, invoices, contracts, and forms — eliminating manual data entry.",
    category: "automation",
    baseImpact: 8,
    baseEffort: 4,
    estimatedROI: "40-60% reduction in document processing time",
    matchIndustries: ["finance", "healthcare", "professional_services", "real_estate"],
    matchDepartments: ["finance", "hr", "legal", "operations"],
    matchObjectives: ["reduce_costs", "improve_efficiency", "reduce_errors"],
    matchBottleneckIds: ["data_entry", "document_processing"],
  },
  {
    id: "predictive_sales",
    title: "Predictive Sales Forecasting",
    description: "Leverage historical data and market signals to predict sales trends, optimize pipeline management, and prioritize high-value opportunities.",
    category: "prediction",
    baseImpact: 8,
    baseEffort: 5,
    estimatedROI: "15-25% improvement in forecast accuracy",
    matchIndustries: ["retail", "technology", "manufacturing", "professional_services"],
    matchDepartments: ["sales", "marketing"],
    matchObjectives: ["increase_revenue", "improve_decision_making"],
    matchBottleneckIds: ["lead_qualification"],
  },
  {
    id: "customer_chatbot",
    title: "AI-Powered Customer Service",
    description: "Deploy conversational AI to handle routine customer inquiries, provide instant responses 24/7, and escalate complex issues to human agents.",
    category: "generative_ai",
    baseImpact: 7,
    baseEffort: 4,
    estimatedROI: "30-50% reduction in support ticket volume",
    matchIndustries: ["retail", "technology", "hospitality", "finance"],
    matchDepartments: ["customer_support", "sales"],
    matchObjectives: ["enhance_customer_experience", "reduce_costs", "scale_operations"],
    matchBottleneckIds: ["customer_response"],
  },
  {
    id: "process_mining",
    title: "Process Mining & Optimization",
    description: "Analyze workflow patterns to identify inefficiencies, bottlenecks, and optimization opportunities across your business operations.",
    category: "analytics",
    baseImpact: 7,
    baseEffort: 6,
    estimatedROI: "20-35% improvement in process efficiency",
    matchIndustries: ["manufacturing", "logistics", "finance", "healthcare"],
    matchDepartments: ["operations", "logistics", "engineering"],
    matchObjectives: ["improve_efficiency", "reduce_costs", "improve_decision_making"],
    matchBottleneckIds: ["approval_workflows", "scheduling"],
  },
  {
    id: "auto_reporting",
    title: "Automated Report Generation",
    description: "Generate comprehensive business reports, dashboards, and summaries automatically from your data sources using AI.",
    category: "automation",
    baseImpact: 6,
    baseEffort: 3,
    estimatedROI: "70-90% reduction in report preparation time",
    matchIndustries: [],
    matchDepartments: ["finance", "marketing", "operations", "sales"],
    matchObjectives: ["improve_efficiency", "improve_decision_making", "reduce_costs"],
    matchBottleneckIds: ["reporting"],
  },
  {
    id: "predictive_maintenance",
    title: "Predictive Maintenance",
    description: "Use sensor data and machine learning to predict equipment failures before they happen, reducing downtime and maintenance costs.",
    category: "prediction",
    baseImpact: 9,
    baseEffort: 7,
    estimatedROI: "25-40% reduction in unplanned downtime",
    matchIndustries: ["manufacturing", "logistics"],
    matchDepartments: ["operations", "engineering"],
    matchObjectives: ["reduce_costs", "improve_efficiency"],
    matchBottleneckIds: ["quality_control"],
  },
  {
    id: "fraud_detection",
    title: "AI Fraud Detection",
    description: "Deploy machine learning models to detect anomalous transactions and patterns in real-time, reducing fraud losses and compliance risks.",
    category: "prediction",
    baseImpact: 9,
    baseEffort: 6,
    estimatedROI: "50-70% improvement in fraud detection rate",
    matchIndustries: ["finance", "retail"],
    matchDepartments: ["finance", "operations"],
    matchObjectives: ["reduce_errors", "reduce_costs"],
    matchBottleneckIds: ["compliance_monitoring"],
  },
  {
    id: "supply_chain",
    title: "Supply Chain Optimization",
    description: "Optimize inventory levels, demand forecasting, and logistics routing using AI to reduce costs and improve delivery performance.",
    category: "optimization",
    baseImpact: 8,
    baseEffort: 7,
    estimatedROI: "15-30% reduction in inventory costs",
    matchIndustries: ["retail", "manufacturing", "logistics"],
    matchDepartments: ["logistics", "operations"],
    matchObjectives: ["reduce_costs", "improve_efficiency", "scale_operations"],
    matchBottleneckIds: ["inventory_management", "scheduling"],
  },
  {
    id: "resume_screening",
    title: "AI Resume Screening & Candidate Matching",
    description: "Automate resume screening and candidate ranking to accelerate hiring while reducing bias and improving match quality.",
    category: "automation",
    baseImpact: 6,
    baseEffort: 3,
    estimatedROI: "50-70% reduction in screening time",
    matchIndustries: [],
    matchDepartments: ["hr"],
    matchObjectives: ["improve_efficiency", "reduce_costs", "scale_operations"],
    matchBottleneckIds: [],
  },
  {
    id: "sentiment_analysis",
    title: "Customer Sentiment Analysis",
    description: "Analyze customer feedback, reviews, and social media to understand sentiment trends and identify improvement opportunities.",
    category: "analytics",
    baseImpact: 6,
    baseEffort: 4,
    estimatedROI: "Improved NPS scores and customer retention",
    matchIndustries: ["retail", "hospitality", "technology"],
    matchDepartments: ["marketing", "customer_support"],
    matchObjectives: ["enhance_customer_experience", "improve_decision_making"],
    matchBottleneckIds: ["customer_response"],
  },
  {
    id: "content_generation",
    title: "AI Content Generation & Marketing",
    description: "Use generative AI to create marketing copy, product descriptions, email campaigns, and social media content at scale.",
    category: "generative_ai",
    baseImpact: 6,
    baseEffort: 2,
    estimatedROI: "3-5x content production speed",
    matchIndustries: ["retail", "technology", "education", "professional_services"],
    matchDepartments: ["marketing", "sales"],
    matchObjectives: ["increase_revenue", "scale_operations", "accelerate_innovation"],
    matchBottleneckIds: [],
  },
  {
    id: "quality_inspection",
    title: "AI-Powered Quality Inspection",
    description: "Use computer vision and machine learning to automate quality control processes, detect defects, and maintain consistency.",
    category: "automation",
    baseImpact: 8,
    baseEffort: 6,
    estimatedROI: "40-60% reduction in defect rates",
    matchIndustries: ["manufacturing"],
    matchDepartments: ["operations", "engineering"],
    matchObjectives: ["reduce_errors", "improve_efficiency"],
    matchBottleneckIds: ["quality_control"],
  },
  {
    id: "smart_scheduling",
    title: "Intelligent Scheduling & Resource Allocation",
    description: "Optimize staff scheduling, meeting coordination, and resource allocation using AI to maximize utilization and reduce conflicts.",
    category: "optimization",
    baseImpact: 5,
    baseEffort: 3,
    estimatedROI: "20-30% improvement in resource utilization",
    matchIndustries: ["healthcare", "hospitality", "professional_services", "education"],
    matchDepartments: ["operations", "hr"],
    matchObjectives: ["improve_efficiency", "reduce_costs"],
    matchBottleneckIds: ["scheduling"],
  },
  {
    id: "compliance_automation",
    title: "Compliance Monitoring & Automation",
    description: "Automate compliance checks, regulatory monitoring, and audit preparation using AI to reduce risk and manual oversight.",
    category: "automation",
    baseImpact: 7,
    baseEffort: 5,
    estimatedROI: "50-70% reduction in compliance processing time",
    matchIndustries: ["finance", "healthcare", "real_estate"],
    matchDepartments: ["legal", "finance", "operations"],
    matchObjectives: ["reduce_errors", "reduce_costs", "improve_efficiency"],
    matchBottleneckIds: ["compliance_monitoring"],
  },
  {
    id: "knowledge_management",
    title: "AI Knowledge Base & Internal Search",
    description: "Build an intelligent knowledge management system that lets employees find answers instantly from internal documents, wikis, and past communications.",
    category: "generative_ai",
    baseImpact: 6,
    baseEffort: 4,
    estimatedROI: "30-50% reduction in time searching for information",
    matchIndustries: [],
    matchDepartments: ["engineering", "customer_support", "operations"],
    matchObjectives: ["improve_efficiency", "scale_operations", "accelerate_innovation"],
    matchBottleneckIds: ["document_processing"],
  },
];
